apiVersion: apps/v1
kind: Deployment
metadata:
 name: testrepo
spec:
 selector:
   matchLabels:
     app: testrepo
 replicas: 1
 template:
   metadata:
     labels:
       app: testrepo
   spec:
     containers:
     - name: testrepo
       image: gcr.io/yj-pro/im:v1
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
       ports:
       - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
 name: testrepo
spec:
 type: LoadBalancer
 selector:
   app: testrepo
 ports:
 - name: http
   port: 8080
   targetPort: 8080

