steps:
- name: 'gcr.io/yj-pro/ubuntu-curl'
  args: ['bash', '-c', 'curl https://api.github.com/search/issues?q=repo:yj-toyama/pocpix%20pr:merged%$COMMIT_SHA | grep number | sed "s/ //g" | sed "s/,//g" | sed "s/\"//g" | sed "s/://g"> _TAG']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: [ '-c', 'docker build -t gcr.io/yj-pro/im:$(cat _TAG) .' ]
  id: docker build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker push gcr.io/yj-pro/im:$(cat _TAG)' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', 'testrepo', '--zone', 'asia-northeast1-a', '--project', 'yj-pro' ]
  id: gcloud container clusters get-credentials
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'apps-gcp.yaml' ]
  id: kubectl apply
  env:
    - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
    - "CLOUDSDK_CONTAINER_CLUSTER=testrepo"
