steps:
- name: 'gcr.io/yj-pro/ubuntu-curl'
  args: ['bash', './curl.bash']
- name: 'gcr.io/yj-pro/ubuntu-curl'
  args: ['bash', '-c', 'curl https://api.github.com/search/issues?q=repo:yj-toyama/pocpix%20pr:merged%2083f1e6e1cc38bd212f9a5f6d7e31b0ae62e24550 | grep html_url -m1 | sed \'s/ //g;s/,//g\' > _TAG']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: [ '-c', 'docker build -t gcr.io/yj-pro/im:$(cat _TAG) .' ]
  id: docker build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker push gcr.io/yj-pro/im:$(cat _TAG)' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', 'testrepo', '--zone', 'asia-northeast1-a', '--project', 'yj-pro' ]
  id: gcloud container clusters get-credentials
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'apps-gcp.yaml' ]
  id: kubectl apply
  env:
    - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
    - "CLOUDSDK_CONTAINER_CLUSTER=testrepo"
