steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
                  - "-c"
                  - |
                      RESPONSE=$(curl -i https://api.github.com/search/issues?q=repo:yj-toyama/pocpix%20pr:merged%2083f1e6e1cc38bd212f9a5f6d7e31b0ae62e24550 | grep HTTP | cut -d' ' -f2)
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: [ '-c', 'docker build -t gcr.io/yj-pro/im:$(echo GITUL) .' ]
  id: docker build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker push gcr.io/yj-pro/im:$(echo GITUL)' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', 'testrepo', '--zone', 'asia-northeast1-a', '--project', 'yj-pro' ]
  id: gcloud container clusters get-credentials
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'apps-gcp.yaml' ]
  id: kubectl apply
  env:
    - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
    - "CLOUDSDK_CONTAINER_CLUSTER=testrepo"
