steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: [ '-c', 'docker build -t gcr.io/$PROJECT_ID/im:$COMMIT_SHA .' ]
  id: docker build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  args: ['-c', 'docker push gcr.io/$PROJECT_ID/im:$COMMIT_SHA' ]
  id: docker push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', 'testrepo', '--zone', 'asia-northeast1-a', '--project', '$PROJECT_ID' ]
  id: gcloud container clusters get-credentials
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', 'apps-gcp.yaml' ]
  id: kubectl apply
  env:
    - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
    - "CLOUDSDK_CONTAINER_CLUSTER=testrepo"
substitutions:
    _HASH: $COMMIT_SHA # default value
